version: "3.3"
services:
  nextjs-ui:
    platform: "linux/x86_64"
    build:
      context: "./"
      dockerfile: Dockerfile.dev
    ports:
      - "8080:3000"
    container_name: nextjs-ui
    stdin_open: true
    depends_on:
      - firebase
    volumes:
      - /app/node_modules
      - ./:/app
    restart: always
  firebase:
    platform: "linux/x86_64"
    build:
      context: "./"
      dockerfile: Dockerfile.firebase
    ports:
      - "9099:9099"
      - "5000:5000"
      - "5001:5001"
      - "9199:9199"
      - "4000:4000"
    container_name: firebase
    stdin_open: true
    volumes:
      - /app/node_modules
      - ./:/app
    restart: always
